"""baseline schema

Reproduces the full Argus schema as of Étape 1.2 (diff inter-scans).
Argus est Postgres-only depuis 2026-05 ; sur une nouvelle DB:

    alembic upgrade head

Revision ID: 0001
Revises:
Create Date: 2026-05-14
"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '0001'
down_revision: Union[str, Sequence[str], None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('audit_log',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('ts', sa.Text(), nullable=False),
    sa.Column('username', sa.Text(), nullable=True),
    sa.Column('ip', sa.Text(), nullable=True),
    sa.Column('action', sa.Text(), nullable=False),
    sa.Column('target', sa.Text(), nullable=True),
    sa.Column('details', sa.Text(), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('audit_log', schema=None) as batch_op:
        batch_op.create_index('idx_audit_action', ['action'], unique=False)
        batch_op.create_index('idx_audit_ts', ['ts'], unique=False)
        batch_op.create_index('idx_audit_username', ['username'], unique=False)

    op.create_table('dashboard_runs',
    sa.Column('id', sa.Text(), nullable=False),
    sa.Column('target', sa.Text(), nullable=False),
    sa.Column('mode', sa.Text(), nullable=False),
    sa.Column('modules', sa.Text(), nullable=True),
    sa.Column('pid', sa.Integer(), nullable=True),
    sa.Column('state', sa.Text(), nullable=False),
    sa.Column('started_at', sa.Float(), nullable=False),
    sa.Column('finished_at', sa.Float(), nullable=True),
    sa.Column('returncode', sa.Integer(), nullable=True),
    sa.Column('log_tail', sa.Text(), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('dashboard_runs', schema=None) as batch_op:
        batch_op.create_index('idx_dashboard_runs_state', ['state'], unique=False)
        batch_op.create_index('idx_dashboard_runs_target', ['target'], unique=False)

    op.create_table('findings',
    sa.Column('id', sa.Text(), nullable=False),
    sa.Column('scan_id', sa.Text(), nullable=False),
    sa.Column('domain', sa.Text(), nullable=False),
    sa.Column('type', sa.Text(), nullable=False),
    sa.Column('severity', sa.Text(), nullable=False),
    sa.Column('confidence', sa.Float(), nullable=True),
    sa.Column('title', sa.Text(), nullable=True),
    sa.Column('url', sa.Text(), nullable=True),
    sa.Column('evidence', sa.Text(), nullable=True),
    sa.Column('module_source', sa.Text(), nullable=True),
    sa.Column('tags', sa.Text(), nullable=True),
    sa.Column('metadata', sa.Text(), nullable=True),
    sa.Column('timestamp', sa.Text(), nullable=False),
    sa.Column('is_new', sa.Integer(), server_default='1', nullable=True),
    sa.Column('fingerprint', sa.Text(), nullable=True),
    sa.Column('first_seen_scan_id', sa.Text(), nullable=True),
    sa.Column('last_seen_scan_id', sa.Text(), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('findings', schema=None) as batch_op:
        batch_op.create_index('idx_findings_domain', ['domain'], unique=False)
        batch_op.create_index('idx_findings_fingerprint', ['fingerprint'], unique=False)
        batch_op.create_index('idx_findings_last_seen_scan', ['domain', 'last_seen_scan_id'], unique=False)
        batch_op.create_index('idx_findings_severity', ['severity'], unique=False)

    op.create_table('live_hosts',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('scan_id', sa.Text(), nullable=False),
    sa.Column('domain', sa.Text(), nullable=False),
    sa.Column('url', sa.Text(), nullable=False),
    sa.Column('status_code', sa.Integer(), nullable=True),
    sa.Column('title', sa.Text(), nullable=True),
    sa.Column('technologies', sa.Text(), nullable=True),
    sa.Column('waf', sa.Text(), nullable=True),
    sa.Column('cname', sa.Text(), nullable=True),
    sa.Column('first_seen', sa.Text(), nullable=False),
    sa.Column('first_seen_scan_id', sa.Text(), nullable=True),
    sa.Column('last_seen_scan_id', sa.Text(), nullable=True),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('url', name='uq_live_hosts_url')
    )
    op.create_table('scans',
    sa.Column('scan_id', sa.Text(), nullable=False),
    sa.Column('domain', sa.Text(), nullable=False),
    sa.Column('started_at', sa.Text(), nullable=False),
    sa.Column('finished_at', sa.Text(), nullable=True),
    sa.Column('stats', sa.Text(), nullable=True),
    sa.Column('status', sa.Text(), server_default='running', nullable=True),
    sa.PrimaryKeyConstraint('scan_id')
    )
    op.create_table('subdomains',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('scan_id', sa.Text(), nullable=False),
    sa.Column('domain', sa.Text(), nullable=False),
    sa.Column('subdomain', sa.Text(), nullable=False),
    sa.Column('first_seen', sa.Text(), nullable=False),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('domain', 'subdomain', name='uq_subdomains_domain_subdomain')
    )
    with op.batch_alter_table('subdomains', schema=None) as batch_op:
        batch_op.create_index('idx_subdomains_domain', ['domain'], unique=False)

    op.create_table('users',
    sa.Column('username', sa.Text(), nullable=False),
    sa.Column('password_hash', sa.Text(), nullable=False),
    sa.Column('role', sa.Text(), nullable=False),
    sa.Column('enabled', sa.Integer(), server_default='1', nullable=False),
    sa.Column('created_at', sa.Text(), nullable=False),
    sa.Column('last_login', sa.Text(), nullable=True),
    sa.CheckConstraint("role IN ('super-admin','admin','user')", name='ck_users_role'),
    sa.PrimaryKeyConstraint('username')
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('users')
    with op.batch_alter_table('subdomains', schema=None) as batch_op:
        batch_op.drop_index('idx_subdomains_domain')

    op.drop_table('subdomains')
    op.drop_table('scans')
    op.drop_table('live_hosts')
    with op.batch_alter_table('findings', schema=None) as batch_op:
        batch_op.drop_index('idx_findings_severity')
        batch_op.drop_index('idx_findings_last_seen_scan')
        batch_op.drop_index('idx_findings_fingerprint')
        batch_op.drop_index('idx_findings_domain')

    op.drop_table('findings')
    with op.batch_alter_table('dashboard_runs', schema=None) as batch_op:
        batch_op.drop_index('idx_dashboard_runs_target')
        batch_op.drop_index('idx_dashboard_runs_state')

    op.drop_table('dashboard_runs')
    with op.batch_alter_table('audit_log', schema=None) as batch_op:
        batch_op.drop_index('idx_audit_username')
        batch_op.drop_index('idx_audit_ts')
        batch_op.drop_index('idx_audit_action')

    op.drop_table('audit_log')
    # ### end Alembic commands ###
