"""
Argus V2 — SQLAlchemy 2.0 ORM models.

Single source of truth for the Argus schema. Alembic migrations are
autogenerated from this module ; production runs `alembic upgrade head`
and tests rely on `Base.metadata.create_all(engine)` for ad-hoc setup.

Tables:
    scans          — one row per scan invocation
    subdomains     — UNIQUE(domain, subdomain), first_seen tracker
    live_hosts     — UNIQUE(url), first_seen + tech + diff cols (1.2)
    findings       — fingerprint dedup + first/last_seen_scan_id (1.2)
    dashboard_runs — UI-launched scan processes (PID tracking)
    users          — auth (super-admin/admin/user roles)
    audit_log      — sensitive-action append log
    organisations  — BBP programme container (Étape 2.1)
    targets        — apex ↔ organisation (Étape 2.1)
"""
from __future__ import annotations

from sqlalchemy import (
    BigInteger,
    CheckConstraint,
    Float,
    ForeignKey,
    Index,
    Integer,
    Text,
    UniqueConstraint,
)
from sqlalchemy.dialects.postgresql import JSONB
from sqlalchemy.orm import DeclarativeBase, Mapped, mapped_column
from typing import Any, Optional


class Base(DeclarativeBase):
    """SQLAlchemy 2.0 declarative base for all Argus tables."""
    pass


class Scan(Base):
    __tablename__ = "scans"

    scan_id:     Mapped[str]           = mapped_column(Text, primary_key=True)
    domain:      Mapped[str]           = mapped_column(Text, nullable=False)
    started_at:  Mapped[str]           = mapped_column(Text, nullable=False)
    finished_at: Mapped[Optional[str]] = mapped_column(Text, nullable=True)
    stats:       Mapped[Optional[str]] = mapped_column(Text, nullable=True)
    status:      Mapped[Optional[str]] = mapped_column(Text, server_default="running")


class Subdomain(Base):
    __tablename__ = "subdomains"
    __table_args__ = (
        UniqueConstraint("domain", "subdomain", name="uq_subdomains_domain_subdomain"),
        Index("idx_subdomains_domain", "domain"),
        Index("idx_subdomains_attributed_apex", "attributed_apex"),
    )

    id:               Mapped[int] = mapped_column(Integer, primary_key=True, autoincrement=True)
    scan_id:          Mapped[str] = mapped_column(Text, nullable=False)
    domain:           Mapped[str] = mapped_column(Text, nullable=False)
    subdomain:        Mapped[str] = mapped_column(Text, nullable=False)
    first_seen:       Mapped[str] = mapped_column(Text, nullable=False)
    # Attribution (Étape 0003) : most-specific apex from targets.apex that
    # owns this subdomain via longest-suffix match. NULL = orphan / shadow IT.
    attributed_apex:  Mapped[Optional[str]] = mapped_column(Text, nullable=True)


class LiveHost(Base):
    __tablename__ = "live_hosts"
    __table_args__ = (
        UniqueConstraint("url", name="uq_live_hosts_url"),
        Index("idx_live_hosts_attributed_apex", "attributed_apex"),
    )

    id:                  Mapped[int]           = mapped_column(Integer, primary_key=True, autoincrement=True)
    scan_id:             Mapped[str]           = mapped_column(Text, nullable=False)
    domain:              Mapped[str]           = mapped_column(Text, nullable=False)
    url:                 Mapped[str]           = mapped_column(Text, nullable=False)
    status_code:         Mapped[Optional[int]] = mapped_column(Integer, nullable=True)
    title:               Mapped[Optional[str]] = mapped_column(Text, nullable=True)
    technologies:        Mapped[Optional[str]] = mapped_column(Text, nullable=True)  # JSON-encoded list
    waf:                 Mapped[Optional[str]] = mapped_column(Text, nullable=True)
    cname:               Mapped[Optional[str]] = mapped_column(Text, nullable=True)
    first_seen:          Mapped[str]           = mapped_column(Text, nullable=False)
    # Diff tracking (Étape 1.2)
    first_seen_scan_id:  Mapped[Optional[str]] = mapped_column(Text, nullable=True)
    last_seen_scan_id:   Mapped[Optional[str]] = mapped_column(Text, nullable=True)
    # Attribution (Étape 0003) — see Subdomain.attributed_apex
    attributed_apex:     Mapped[Optional[str]] = mapped_column(Text, nullable=True)


class Finding(Base):
    __tablename__ = "findings"
    __table_args__ = (
        Index("idx_findings_domain", "domain"),
        Index("idx_findings_severity", "severity"),
        Index("idx_findings_fingerprint", "fingerprint"),
        Index("idx_findings_last_seen_scan", "domain", "last_seen_scan_id"),
        Index("idx_findings_attributed_apex", "attributed_apex"),
    )

    id:                  Mapped[str]             = mapped_column(Text, primary_key=True)
    scan_id:             Mapped[str]             = mapped_column(Text, nullable=False)
    domain:              Mapped[str]             = mapped_column(Text, nullable=False)
    type:                Mapped[str]             = mapped_column(Text, nullable=False)
    severity:            Mapped[str]             = mapped_column(Text, nullable=False)
    confidence:          Mapped[Optional[float]] = mapped_column(Float, nullable=True)
    title:               Mapped[Optional[str]]   = mapped_column(Text, nullable=True)
    url:                 Mapped[Optional[str]]   = mapped_column(Text, nullable=True)
    evidence:            Mapped[Optional[str]]   = mapped_column(Text, nullable=True)
    module_source:       Mapped[Optional[str]]   = mapped_column(Text, nullable=True)
    tags:                Mapped[Optional[str]]   = mapped_column(Text, nullable=True)      # JSON list
    metadata_json:       Mapped[Optional[str]]   = mapped_column("metadata", Text, nullable=True)  # JSON dict; SQL col name kept as `metadata` for back-compat
    timestamp:           Mapped[str]             = mapped_column(Text, nullable=False)
    is_new:              Mapped[Optional[int]]   = mapped_column(Integer, server_default="1")
    # Diff tracking (Étape 1.2)
    fingerprint:         Mapped[Optional[str]]   = mapped_column(Text, nullable=True)
    first_seen_scan_id:  Mapped[Optional[str]]   = mapped_column(Text, nullable=True)
    last_seen_scan_id:   Mapped[Optional[str]]   = mapped_column(Text, nullable=True)
    # Attribution (Étape 0003) — see Subdomain.attributed_apex
    attributed_apex:     Mapped[Optional[str]]   = mapped_column(Text, nullable=True)


class DashboardRun(Base):
    __tablename__ = "dashboard_runs"
    __table_args__ = (
        Index("idx_dashboard_runs_target", "target"),
        Index("idx_dashboard_runs_state",  "state"),
    )

    id:          Mapped[str]             = mapped_column(Text, primary_key=True)
    target:      Mapped[str]             = mapped_column(Text, nullable=False)
    mode:        Mapped[str]             = mapped_column(Text, nullable=False)
    modules:     Mapped[Optional[str]]   = mapped_column(Text, nullable=True)
    pid:         Mapped[Optional[int]]   = mapped_column(Integer, nullable=True)
    state:       Mapped[str]             = mapped_column(Text, nullable=False)
    started_at:  Mapped[float]           = mapped_column(Float, nullable=False)
    finished_at: Mapped[Optional[float]] = mapped_column(Float, nullable=True)
    returncode:  Mapped[Optional[int]]   = mapped_column(Integer, nullable=True)
    log_tail:    Mapped[Optional[str]]   = mapped_column(Text, nullable=True)


class User(Base):
    __tablename__ = "users"
    __table_args__ = (
        CheckConstraint(
            "role IN ('super-admin','admin','user')",
            name="ck_users_role",
        ),
    )

    username:      Mapped[str]           = mapped_column(Text, primary_key=True)
    password_hash: Mapped[str]           = mapped_column(Text, nullable=False)
    role:          Mapped[str]           = mapped_column(Text, nullable=False)
    enabled:       Mapped[int]           = mapped_column(Integer, nullable=False, server_default="1")
    created_at:    Mapped[str]           = mapped_column(Text, nullable=False)
    last_login:    Mapped[Optional[str]] = mapped_column(Text, nullable=True)


class AuditLog(Base):
    __tablename__ = "audit_log"
    __table_args__ = (
        Index("idx_audit_ts",       "ts"),
        Index("idx_audit_username", "username"),
        Index("idx_audit_action",   "action"),
    )

    id:       Mapped[int]           = mapped_column(Integer, primary_key=True, autoincrement=True)
    ts:       Mapped[str]           = mapped_column(Text, nullable=False)
    username: Mapped[Optional[str]] = mapped_column(Text, nullable=True)
    ip:       Mapped[Optional[str]] = mapped_column(Text, nullable=True)
    action:   Mapped[str]           = mapped_column(Text, nullable=False)
    target:   Mapped[Optional[str]] = mapped_column(Text, nullable=True)
    details:  Mapped[Optional[str]] = mapped_column(Text, nullable=True)


# ─────────────────────────────────────────────────────────────────────
# Multi-org (Étape 2.1)
# ─────────────────────────────────────────────────────────────────────
# Volontairement découplé des autres tables : pas de FK ajoutée sur
# scans/findings/etc. La résolution domain → target → organisation se
# fait via JOIN au moment des queries. Trade-off : pas de cascade DB,
# mais pas de migration destructive sur 7 tables existantes non plus.

class Organisation(Base):
    __tablename__ = "organisations"
    __table_args__ = (
        UniqueConstraint("name", name="uq_organisations_name"),
        Index("idx_organisations_name", "name"),
    )

    id:           Mapped[int]           = mapped_column(Integer, primary_key=True, autoincrement=True)
    name:         Mapped[str]           = mapped_column(Text, nullable=False)
    h1_handle:    Mapped[Optional[str]] = mapped_column(Text, nullable=True)
    scope_file:   Mapped[Optional[str]] = mapped_column(Text, nullable=True)  # path to scopes/<x>.yaml
    notes:        Mapped[Optional[str]] = mapped_column(Text, nullable=True)
    created_at:   Mapped[str]           = mapped_column(Text, nullable=False)


class Target(Base):
    __tablename__ = "targets"
    __table_args__ = (
        Index("idx_targets_org", "organisation_id"),
    )

    # apex is the natural PK — same key used everywhere as `domain`.
    apex:                 Mapped[str]           = mapped_column(Text, primary_key=True)
    organisation_id:      Mapped[Optional[int]] = mapped_column(
        Integer, ForeignKey("organisations.id", ondelete="SET NULL"), nullable=True,
    )
    scope_file_override:  Mapped[Optional[str]] = mapped_column(Text, nullable=True)
    notes:                Mapped[Optional[str]] = mapped_column(Text, nullable=True)
    created_at:           Mapped[str]           = mapped_column(Text, nullable=False)


# ─────────────────────────────────────────────────────────────────────
# CVE intelligence (Étape 0004) — fondation du chantier CVE.
# ─────────────────────────────────────────────────────────────────────
# `cves` est le référentiel pull-from-feeds (NVD/KEV/EPSS/nuclei-templates).
# `surface_intel` cache les observations Shodan/Censys/Fofa/…
# `cve_matches` est l'épine dorsale : asset ↔ CVE avec méthode + confidence
# + état de validation. Toutes les colonnes JSON sont encodées en Text
# pour rester cohérent avec le reste du schéma Argus.

class CVE(Base):
    __tablename__ = "cves"
    __table_args__ = (
        Index("idx_cves_published_at", "published_at"),
        Index("idx_cves_cvss_v3",      "cvss_v3"),
        Index("idx_cves_epss",         "epss"),
        Index("idx_cves_kev_flag",     "kev_flag"),
        Index("idx_cves_vendor",       "vendor"),
    )

    cve_id:           Mapped[str]             = mapped_column(Text, primary_key=True)
    published_at:     Mapped[Optional[str]]   = mapped_column(Text, nullable=True)
    cvss_v3:          Mapped[Optional[float]] = mapped_column(Float, nullable=True)
    cvss_v3_vector:   Mapped[Optional[str]]   = mapped_column(Text, nullable=True)
    cvss_v2:          Mapped[Optional[float]] = mapped_column(Float, nullable=True)
    epss:             Mapped[Optional[float]] = mapped_column(Float, nullable=True)
    epss_percentile:  Mapped[Optional[float]] = mapped_column(Float, nullable=True)
    # SQLite/Postgres bool stocké en Integer (0/1) pour rester portable.
    kev_flag:         Mapped[int]             = mapped_column(Integer, nullable=False, server_default="0")
    kev_added_at:     Mapped[Optional[str]]   = mapped_column(Text, nullable=True)
    kev_ransomware:   Mapped[int]             = mapped_column(Integer, nullable=False, server_default="0")
    description:      Mapped[Optional[str]]   = mapped_column(Text, nullable=True)
    vendor:           Mapped[Optional[str]]   = mapped_column(Text, nullable=True)
    cpes:             Mapped[Optional[str]]   = mapped_column(Text, nullable=True)   # JSON list raw CPEs
    products:         Mapped[Optional[str]]   = mapped_column(Text, nullable=True)   # JSON normalized
    refs:             Mapped[Optional[str]]   = mapped_column(Text, nullable=True)   # JSON list URLs
    nuclei_template:  Mapped[Optional[str]]   = mapped_column(Text, nullable=True)
    source_feeds:     Mapped[Optional[str]]   = mapped_column(Text, nullable=True)   # JSON ["nvd","kev","epss"]
    created_at:       Mapped[str]             = mapped_column(Text, nullable=False)
    updated_at:       Mapped[str]             = mapped_column(Text, nullable=False)


class SurfaceIntel(Base):
    __tablename__ = "surface_intel"
    __table_args__ = (
        Index("idx_surface_intel_source",     "source"),
        Index("idx_surface_intel_ip",         "ip"),
        Index("idx_surface_intel_ip_port",    "ip", "port"),
        Index("idx_surface_intel_country",    "country"),
        Index("idx_surface_intel_asn",        "asn"),
        Index("idx_surface_intel_product",    "product"),
        Index("idx_surface_intel_attributed", "attributed_apex"),
    )

    id:              Mapped[int]             = mapped_column(BigInteger, primary_key=True, autoincrement=True)
    source:          Mapped[str]             = mapped_column(Text, nullable=False)   # shodan|censys|fofa|...
    ip:              Mapped[str]             = mapped_column(Text, nullable=False)
    port:            Mapped[Optional[int]]   = mapped_column(Integer, nullable=True)
    product:         Mapped[Optional[str]]   = mapped_column(Text, nullable=True)
    version:         Mapped[Optional[str]]   = mapped_column(Text, nullable=True)
    banner_snippet:  Mapped[Optional[str]]   = mapped_column(Text, nullable=True)
    country:         Mapped[Optional[str]]   = mapped_column(Text, nullable=True)
    asn:             Mapped[Optional[int]]   = mapped_column(Integer, nullable=True)
    org_name_raw:    Mapped[Optional[str]]   = mapped_column(Text, nullable=True)
    cve_ids:         Mapped[Optional[str]]   = mapped_column(Text, nullable=True)    # JSON list (source-reported)
    hostnames:       Mapped[Optional[str]]   = mapped_column(Text, nullable=True)    # JSON list reverse DNS
    ssl_san:         Mapped[Optional[str]]   = mapped_column(Text, nullable=True)    # JSON list cert SANs
    ptr:             Mapped[Optional[str]]   = mapped_column(Text, nullable=True)
    payload:         Mapped[Optional[str]]   = mapped_column(Text, nullable=True)    # JSON raw (audit)
    attributed_apex: Mapped[Optional[str]]   = mapped_column(Text, nullable=True)
    pivot_method:    Mapped[Optional[str]]   = mapped_column(Text, nullable=True)
    observed_at:     Mapped[str]             = mapped_column(Text, nullable=False)


class CVEMatch(Base):
    """Asset ↔ CVE — l'épine dorsale du chantier CVE intelligence.

    L'unicité (cve_id, asset_url, asset_ip, asset_port, match_method) garantit
    l'idempotence : re-run d'un correlator ne duplique pas.
    """
    __tablename__ = "cve_matches"
    __table_args__ = (
        UniqueConstraint(
            "cve_id", "asset_url", "asset_ip", "asset_port", "match_method",
            name="uq_cve_matches_target_method",
        ),
        Index("idx_cve_matches_cve_id",           "cve_id"),
        Index("idx_cve_matches_attributed",       "attributed_apex"),
        Index("idx_cve_matches_organisation",     "organisation_id"),
        Index("idx_cve_matches_validation_state", "validation_state"),
        Index("idx_cve_matches_match_source",     "match_source"),
    )

    id:                Mapped[int]             = mapped_column(BigInteger, primary_key=True, autoincrement=True)
    cve_id:            Mapped[str]             = mapped_column(
        Text, ForeignKey("cves.cve_id", ondelete="CASCADE"), nullable=False,
    )
    # Méthode de matching (template / version / name_only / surface_*)
    match_method:      Mapped[str]             = mapped_column(Text, nullable=False)
    match_source:      Mapped[str]             = mapped_column(Text, nullable=False)  # internal|external
    # Asset
    asset_host:        Mapped[Optional[str]]   = mapped_column(Text, nullable=True)
    asset_ip:          Mapped[Optional[str]]   = mapped_column(Text, nullable=True)
    asset_url:         Mapped[Optional[str]]   = mapped_column(Text, nullable=True)
    asset_port:        Mapped[Optional[int]]   = mapped_column(Integer, nullable=True)
    asset_product:     Mapped[Optional[str]]   = mapped_column(Text, nullable=True)
    asset_version:     Mapped[Optional[str]]   = mapped_column(Text, nullable=True)
    version_required:  Mapped[Optional[str]]   = mapped_column(Text, nullable=True)
    # Attribution (réutilise le mécanisme Étape 0003)
    attributed_apex:   Mapped[Optional[str]]   = mapped_column(Text, nullable=True)
    organisation_id:   Mapped[Optional[int]]   = mapped_column(
        Integer, ForeignKey("organisations.id", ondelete="SET NULL"), nullable=True,
    )
    pivot_method:      Mapped[Optional[str]]   = mapped_column(Text, nullable=True)
    # Statut
    confidence:        Mapped[float]           = mapped_column(Float, nullable=False, server_default="0.5")
    validation_state:  Mapped[str]             = mapped_column(Text, nullable=False, server_default="'candidate'")
    validated_at:      Mapped[Optional[str]]   = mapped_column(Text, nullable=True)
    validated_by:      Mapped[Optional[str]]   = mapped_column(Text, nullable=True)
    evidence:          Mapped[Optional[str]]   = mapped_column(Text, nullable=True)    # JSON
    # Temporel
    first_seen_at:     Mapped[str]             = mapped_column(Text, nullable=False)
    last_seen_at:      Mapped[str]             = mapped_column(Text, nullable=False)


# ─────────────────────────────────────────────────────────────────────
# Module artefacts (Étape 0006) — structured per-module output in Postgres.
# ─────────────────────────────────────────────────────────────────────
# Generic home for the structured, per-item module outputs that used to live
# only as JSON files under output/<domain>/ (js_secrets, js_endpoints,
# takeovers, patterns, tech, email_security, …). Promoting them to the DB
# gives the dashboard a single source of truth, plus diff/history/scoping for
# free — the same wins findings/live_hosts already get.
#
# Design:
#   - `kind` is the logical artefact class (e.g. 'js_secret'), `module` the
#     producer ('m11'). Together with `domain` they form the query identity:
#     the dashboard fetches `WHERE domain=? AND kind=?`.
#   - `dedup_key` is a stable per-item identity *within* (domain, module, kind)
#     so re-scans upsert in place and we can diff (first/last_seen_scan_id),
#     mirroring findings.fingerprint and live_hosts.url.
#   - `data` is JSONB (not Text-JSON like the rest of the schema): the whole
#     point of this table is queryability, so we deliberately break the
#     convention to allow `data @> '{...}'` / `data->>'severity'` filters.
#     Postgres-only runtime makes this safe.
class ScanArtefact(Base):
    __tablename__ = "scan_artefacts"
    __table_args__ = (
        # Cross-scan identity: same logical item upserts in place so diff works.
        UniqueConstraint(
            "domain", "module", "kind", "dedup_key",
            name="uq_scan_artefacts_identity",
        ),
        Index("idx_scan_artefacts_domain_kind", "domain", "kind"),
        Index("idx_scan_artefacts_scan",        "scan_id"),
        Index("idx_scan_artefacts_last_seen",   "domain", "kind", "last_seen_scan_id"),
    )

    id:                  Mapped[int]           = mapped_column(BigInteger, primary_key=True, autoincrement=True)
    scan_id:             Mapped[str]           = mapped_column(Text, nullable=False)
    domain:              Mapped[str]           = mapped_column(Text, nullable=False)
    module:              Mapped[str]           = mapped_column(Text, nullable=False)   # 'm11'
    kind:                Mapped[str]           = mapped_column(Text, nullable=False)   # 'js_secret'
    dedup_key:           Mapped[str]           = mapped_column(Text, nullable=False)
    data:                Mapped[Any]           = mapped_column(JSONB, nullable=False)
    # Diff tracking — same scheme as findings / live_hosts.
    first_seen_scan_id:  Mapped[Optional[str]] = mapped_column(Text, nullable=True)
    last_seen_scan_id:   Mapped[Optional[str]] = mapped_column(Text, nullable=True)
    created_at:          Mapped[str]           = mapped_column(Text, nullable=False)
    updated_at:          Mapped[str]           = mapped_column(Text, nullable=False)
